# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zipcode',
            fields=[
                ('zip_code', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='CEP')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Logradouro')),
                ('neighborhood', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bairro')),
                ('state', models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cidade')),
            ],
        ),
    ]
